Repository asyncapi/bindings, pull requests merged in 2023-11, with the labels that each got.

#143 docs: make usage of Schema Object consistent
  anypointmq/README.md
  anypointmq/json_schemas/message.json
  http/README.md
  http/json_schemas/message.json
  http/json_schemas/operation.json
  kafka/README.md
  kafka/json_schemas/message.json
  websockets/README.md
  websockets/json_schemas/channel.json
Labels: stale, ready-to-merge

#225 chore: update next-major-spec with master
  .github/workflows/automerge.yml
  .github/workflows/help-command.yml
  CODEOWNERS
  anypointmq/README.md
  http/README.md
  jms/README.md
  kafka/README.md
  sns/README.md
  sns/SNS-HTTP.png
  sns/SNS-SQS-Pub-Sub.png
  sqs/README.md
  sqs/SNS-SQS-Pub-Sub.png
  sqs/SQS-Point-To-Point.png
  websockets/README.md
Labels: do-not-merge

#203 feat: adapt anypointmq bindings to v3
  anypointmq/README.md
Labels: ready-to-merge
