Repository asyncapi/bindings, pull requests merged in 2023-06, with the labels that each got.

#208 chore: update next-major-spec with master
  .github/workflows/add-good-first-issue-labels.yml
  .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
  .github/workflows/automerge-for-humans-merging.yml
  .github/workflows/automerge-for-humans-remove-ready-to-merge-label-on-edit.yml
  .github/workflows/automerge-orphans.yml
  .github/workflows/automerge.yml
  .github/workflows/autoupdate.yml
  .github/workflows/help-command.yml
  .github/workflows/if-go-pr-testing.yml
  .github/workflows/if-nodejs-pr-testing.yml
  .github/workflows/if-nodejs-release.yml
  .github/workflows/if-nodejs-version-bump.yml
  .github/workflows/issues-prs-notifications.yml
  .github/workflows/lint-pr-title.yml
  .github/workflows/notify-tsc-members-mention.yml
  .github/workflows/release-announcements.yml
  .github/workflows/scripts/README.md
  .github/workflows/scripts/mailchimp/htmlContent.js
  .github/workflows/scripts/mailchimp/index.js
  .github/workflows/scripts/mailchimp/package-lock.json
  .github/workflows/scripts/mailchimp/package.json
  .github/workflows/sentiment-analysis.yml
  .github/workflows/stale-issues-prs.yml
  .github/workflows/welcome-first-time-contrib.yml
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  anypointmq/README.md
  anypointmq/json_schemas/channel.json
  anypointmq/json_schemas/message.json
  googlepubsub/README.md
  googlepubsub/json_schemas/channel.json
  googlepubsub/json_schemas/message.json
  http/README.md
  ibmmq/README.md
  ibmmq/json_schemas/channel.json
  kafka/README.md
  kafka/json_schemas/channel.json
  kafka/json_schemas/message.json
  kafka/json_schemas/operation.json
  kafka/json_schemas/server.json
  mqtt/README.md
  mqtt5/README.md
  mqtt5/json_schemas/server.json
  nats/README.md
  nats/json_schemas/operation.json
  pulsar/README.md
  pulsar/json_schemas/channel.json
  pulsar/json_schemas/server.json
  solace/README.md
  solace/json_schemas/operation.json
  solace/json_schemas/server.json
Labels: do-not-merge

#193 feat: first draft of JMS Binding Objects
  CODEOWNERS
  jms/README.md
  jms/json_schemas/channel.json
  jms/json_schemas/message.json
  jms/json_schemas/server.json
Labels: ready-to-merge

#184 fix: removed all json-schemas file
  amqp/json_schemas/channel.json
  amqp/json_schemas/message.json
  amqp/json_schemas/operation.json
  anypointmq/json_schemas/channel.json
  anypointmq/json_schemas/message.json
  googlepubsub/json_schemas/channel.json
  googlepubsub/json_schemas/message.json
  http/json_schemas/message.json
  http/json_schemas/operation.json
  ibmmq/json_schemas/channel.json
  ibmmq/json_schemas/message.json
  ibmmq/json_schemas/server.json
  kafka/json_schemas/channel.json
  kafka/json_schemas/message.json
  kafka/json_schemas/operation.json
  kafka/json_schemas/server.json
  mqtt/json_schemas/message.json
  mqtt/json_schemas/operation.json
  mqtt/json_schemas/server.json
  mqtt5/json_schemas/server.json
  nats/json_schemas/operation.json
  pulsar/json_schemas/channel.json
  pulsar/json_schemas/server.json
  solace/json_schemas/operation.json
  solace/json_schemas/server.json
  websockets/json_schemas/channel.json
Labels: ready-to-merge, do-not-merge
